name:  Build Docker on Remote Machine

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on:  self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Build Docker Image
        run: COMPOSE_BAKE=true && docker compose up -d --build
